package entity;
// Generated Dec 17, 2016 9:38:37 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clothes generated by hbm2java
 */
@Entity
@Table(name="clothes"
    ,catalog="dbbook"
)
public class Clothes  implements java.io.Serializable {


     private int id;
     private String name;
     private String imgUrl;
     private String desciption;

    public Clothes() {
    }

	
    public Clothes(int id) {
        this.id = id;
    }
    public Clothes(int id, String name, String imgUrl, String desciption) {
       this.id = id;
       this.name = name;
       this.imgUrl = imgUrl;
       this.desciption = desciption;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Name", length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="imgURL", length=500)
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    
    @Column(name="Desciption", length=65535)
    public String getDesciption() {
        return this.desciption;
    }
    
    public void setDesciption(String desciption) {
        this.desciption = desciption;
    }

    @Override
    public String toString() {
        return "Clothes{" + "id=" + id + ", name=" + name + ", imgUrl=" + imgUrl + ", desciption=" + desciption + '}';
    }




}


